services:
  - type: web
    name: deepfake-detection-backend
    env: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "gunicorn --config gunicorn_config.py wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
    plan: free
    autoDeploy: true
    healthCheckPath: / 