services:
  - type: web
    name: deepfake-detection-backend
    env: docker
    healthCheckPath: /
    autoDeploy: true
    plan: free
    envVars:
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
      - key: PYTHON_VERSION
        value: "3.9.18" 