services:
  - type: web
    name: deepfake-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py wsgi:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    plan: free
    healthCheckPath: /
    autoDeploy: true 